### ISSUE TITLE
What error message is this? How can I solve this problem?

### ISSUE THREAD

**Issue by nhj7** [Netherdrake/steem-python#5]
root@ubuntu:~# steempy
Traceback (most recent call last):
  File "/usr/local/bin/steempy", line 7, in <module>
    from steem.cli import legacy
  File "/usr/local/lib/python3.5/dist-packages/steem/__init__.py", line 2, in <module>
    from .steem import Steem
  File "/usr/local/lib/python3.5/dist-packages/steem/steem.py", line 1, in <module>
    from .commit import Commit
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 20, in <module>
    from .account import Account
  File "/usr/local/lib/python3.5/dist-packages/steem/account.py", line 8, in <module>
    from funcy.simple_funcs import rpartial
ImportError: No module named 'funcy.simple_funcs'

**Comment by biophil** [comment]
Pip doesn't install the latest version. I've been getting around this by manually installing the library:

```
git clone https://github.com/Netherdrake/steem-python
cd steem-python
sudo python3 setup.py install
```
