### ISSUE TITLE
ContextualVersionConflict

### ISSUE THREAD

**Issue by jaredcwillis** [Netherdrake/steem-python#6]
jared@debian:~$ steempy addaccount
Traceback (most recent call last):
  File "/home/jared/anaconda3/bin/steempy", line 7, in <module>
    steem.cli.legacy()
  File "/home/jared/anaconda3/lib/python3.6/site-packages/steem/cli.py", line 83, in legacy
    version=pkg_resources.require("steem")[0].version
  File "/home/jared/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jared/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (toml 0.9.3 (/home/jared/anaconda3/lib/python3.6/site-packages), Requirement.parse('toml==0.9.3.1'), {'steem'})

**Comment by jaredcwillis** [comment]
I'm sorry, ignore me. This is an issue with my environment.
