### ISSUE TITLE
$ pip install -U steem produces following error, Any solutions?

### ISSUE THREAD

**Issue by sureshvmax** [Netherdrake/steem-python#7]
$python3.6 -m pip install steem
Collecting steem
  Using cached steem-0.18.103.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9i5v1kel/steem/setup.py", line 8, in <module>
        import package_meta # this is a simple tool for loading metadata from Pipfile and other places
      File "/tmp/pip-build-9i5v1kel/steem/package_meta.py", line 10, in <module>
        from setuptools.config import read_configuration
    ModuleNotFoundError: No module named 'setuptools.config'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ModuleNotFoundError: No module named 'apt_pkg'

    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9i5v1kel/steem/setup.py", line 8, in <module>
        import package_meta # this is a simple tool for loading metadata from Pipfile and other places
      File "/tmp/pip-build-9i5v1kel/steem/package_meta.py", line 10, in <module>
        from setuptools.config import read_configuration
    ModuleNotFoundError: No module named 'setuptools.config'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9i5v1kel/steem/

**Comment by sureshvmax** [comment]
This issue has been sorted by updating setuptools
`sudo python3.6 -m pip install -U pip setuptools`
